Repository rrd108/vue-mess-detector, pull requests merged in 2024-08, with the labels that each got.

#102 feat: add vue-caution/element-selectors-with-scoped
  README.md
  docs/rules/vue-caution/element-selectors-with-scoped.md
  docs/rules/vue-caution/index.md
  package.json
  src/rules/rules.ts
  src/rules/vue-caution/elementSelectorsWithScoped.test.ts
  src/rules/vue-caution/elementSelectorsWithScoped.ts
  src/rulesCheck.ts
  src/rulesReport.ts
  yarn.lock
Labels: invalid

#108 feat: enable --group cli option to group results by rule or file
  src/analyzer.ts
  src/index.ts
  src/rules/rrd/cyclomaticComplexity.test.ts
  src/rules/rrd/cyclomaticComplexity.ts
  src/rules/rrd/deepIndentation.test.ts
  src/rules/rrd/deepIndentation.ts
  src/rules/rrd/elseCondition.test.ts
  src/rules/rrd/elseCondition.ts
  src/rules/rrd/functionSize.test.ts
  src/rules/rrd/functionSize.ts
  src/rules/rrd/parameterCount.test.ts
  src/rules/rrd/parameterCount.ts
  src/rules/rrd/plainScript.ts
  src/rules/rrd/scriptLength.test.ts
  src/rules/rrd/scriptLength.ts
  src/rules/rrd/shortVariableName.test.ts
  src/rules/rrd/shortVariableName.ts
  src/rules/rrd/tooManyProps.test.ts
  src/rules/rrd/tooManyProps.ts
  src/rules/vue-caution/implicitParentChildCommunication.test.ts
  src/rules/vue-caution/implicitParentChildCommunication.ts
  src/rules/vue-essential/globalStyle.test.ts
  src/rules/vue-essential/globalStyle.ts
  src/rules/vue-essential/simpleProp.test.ts
  src/rules/vue-essential/simpleProp.ts
  src/rules/vue-essential/singeNameComponent.test.ts
  src/rules/vue-essential/singleNameComponent.test.ts
  src/rules/vue-essential/singleNameComponent.ts
  src/rules/vue-essential/vforNoKey.test.ts
  src/rules/vue-essential/vforNoKey.ts
  src/rules/vue-essential/vifWithVfor.test.ts
  src/rules/vue-essential/vifWithVfor.ts
  src/rules/vue-recommended/elementAttributeOrder.test.ts
  src/rules/vue-recommended/elementAttributeOrder.ts
  src/rules/vue-recommended/topLevelElementOrder.test.ts
  src/rules/vue-recommended/topLevelElementOrder.ts
  src/rules/vue-strong/componentFilenameCasing.test.ts
  src/rules/vue-strong/componentFilenameCasing.ts
  src/rules/vue-strong/componentFiles.test.ts
  src/rules/vue-strong/componentFiles.ts
  src/rules/vue-strong/directiveShorthands.test.ts
  src/rules/vue-strong/directiveShorthands.ts
  src/rules/vue-strong/fullWordComponentName.test.ts
  src/rules/vue-strong/fullWordComponentName.ts
  src/rules/vue-strong/propNameCasing.test.ts
  src/rules/vue-strong/propNameCasing.ts
  src/rules/vue-strong/quotedAttributeValues.test.ts
  src/rules/vue-strong/quotedAttributeValues.ts
  src/rules/vue-strong/selfClosingComponents.test.ts
  src/rules/vue-strong/selfClosingComponents.ts
  src/rules/vue-strong/simpleComputed.test.ts
  src/rules/vue-strong/simpleComputed.ts
  src/rules/vue-strong/templateSimpleExpression.test.ts
  src/rules/vue-strong/templateSimpleExpression.ts
  src/rulesReport.ts
  src/types/index.ts
Labels: enhancement

#125 refactor: update links in all rules output to our docs site
  src/rules/rrd/cyclomaticComplexity.test.ts
  src/rules/rrd/cyclomaticComplexity.ts
  src/rules/rrd/deepIndentation.test.ts
  src/rules/rrd/deepIndentation.ts
  src/rules/rrd/elseCondition.test.ts
  src/rules/rrd/elseCondition.ts
  src/rules/rrd/functionSize.test.ts
  src/rules/rrd/functionSize.ts
  src/rules/rrd/magicNumbers.test.ts
  src/rules/rrd/magicNumbers.ts
  src/rules/rrd/parameterCount.test.ts
  src/rules/rrd/parameterCount.ts
  src/rules/rrd/plainScript.ts
  src/rules/rrd/scriptLength.test.ts
  src/rules/rrd/scriptLength.ts
  src/rules/rrd/shortVariableName.test.ts
  src/rules/rrd/shortVariableName.ts
  src/rules/rrd/tooManyProps.test.ts
  src/rules/rrd/tooManyProps.ts
  src/rules/vue-caution/elementSelectorsWithScoped.test.ts
  src/rules/vue-caution/elementSelectorsWithScoped.ts
  src/rules/vue-caution/implicitParentChildCommunication.test.ts
  src/rules/vue-caution/implicitParentChildCommunication.ts
  src/rules/vue-essential/globalStyle.test.ts
  src/rules/vue-essential/globalStyle.ts
  src/rules/vue-essential/simpleProp.test.ts
  src/rules/vue-essential/simpleProp.ts
  src/rules/vue-essential/singleNameComponent.test.ts
  src/rules/vue-essential/singleNameComponent.ts
  src/rules/vue-essential/vforNoKey.test.ts
  src/rules/vue-essential/vforNoKey.ts
  src/rules/vue-essential/vifWithVfor.test.ts
  src/rules/vue-essential/vifWithVfor.ts
  src/rules/vue-recommended/elementAttributeOrder.test.ts
  src/rules/vue-recommended/elementAttributeOrder.ts
  src/rules/vue-recommended/topLevelElementOrder.test.ts
  src/rules/vue-recommended/topLevelElementOrder.ts
  src/rules/vue-strong/componentFilenameCasing.test.ts
  src/rules/vue-strong/componentFilenameCasing.ts
  src/rules/vue-strong/componentFiles.test.ts
  src/rules/vue-strong/componentFiles.ts
  src/rules/vue-strong/directiveShorthands.test.ts
  src/rules/vue-strong/directiveShorthands.ts
  src/rules/vue-strong/fullWordComponentName.test.ts
  src/rules/vue-strong/fullWordComponentName.ts
  src/rules/vue-strong/propNameCasing.test.ts
  src/rules/vue-strong/propNameCasing.ts
  src/rules/vue-strong/quotedAttributeValues.test.ts
  src/rules/vue-strong/quotedAttributeValues.ts
  src/rules/vue-strong/selfClosingComponents.test.ts
  src/rules/vue-strong/selfClosingComponents.ts
  src/rules/vue-strong/simpleComputed.test.ts
  src/rules/vue-strong/simpleComputed.ts
  src/rules/vue-strong/templateSimpleExpression.test.ts
  src/rules/vue-strong/templateSimpleExpression.ts
Labels: enhancement

#129 refactor: checkFunctionSize new logic
  src/rules/rrd/functionSize.test.ts
  src/rules/rrd/functionSize.ts
Labels: enhancement

#128 feat: add vue-strong multi attribute element rule plus fixes
  docs/.vitepress/config.ts
  docs/rules/vue-strong/index.md
  docs/rules/vue-strong/multi-attribute-elements.md
  src/rules/rrd/plainScript.test.ts
  src/rules/rrd/plainScript.ts
  src/rules/rules.ts
  src/rules/vue-strong/multiAttributeElements.test.ts
  src/rules/vue-strong/multiAttributeElements.ts
  src/rulesCheck.ts
  src/rulesReport.ts
Labels: enhancement

#124 feat: output explanation
  README.md
  docs/get-started.md
Labels: documentation, enhancement

#136 feat: add rrd if without curly braces rule w tests
  docs/.vitepress/config.ts
  docs/rules/rrd/if-without-curly-braces.md
  docs/rules/rrd/index.md
  src/rules/rrd/ifWithoutCurlyBraces.test.ts
  src/rules/rrd/ifWithoutCurlyBraces.ts
  src/rules/rules.ts
  src/rulesCheck.ts
  src/rulesReport.ts
Labels: enhancement

#131 feat: add rrd props drilling rule w tests
  docs/.vitepress/config.ts
  docs/rules/rrd/index.md
  docs/rules/rrd/props-drilling.md
  src/rules/rrd/propsDrilling.test.ts
  src/rules/rrd/propsDrilling.ts
  src/rules/rules.ts
  src/rulesCheck.ts
  src/rulesReport.ts
Labels: enhancement

#133 docs: add code examples
  docs/.vitepress/config.ts
  docs/rules/rrd/cyclomatic-complexity.md
  docs/rules/rrd/deep-indentation.md
  docs/rules/rrd/else-condition.md
  docs/rules/rrd/function-size.md
  docs/rules/rrd/parameter-count.md
  docs/rules/rrd/plain-script.md
  docs/rules/rrd/script-length.md
  docs/rules/rrd/short-variable-name.md
  docs/rules/rrd/too-many-props.md
  docs/rules/vue-caution/element-selectors-with-scoped.md
  docs/rules/vue-caution/implicit-parent-child-communication.md
  docs/rules/vue-essential/global-style.md
  docs/rules/vue-essential/simple-prop.md
  docs/rules/vue-essential/single-name-component.md
  docs/rules/vue-essential/vfor-no-key.md
  docs/rules/vue-essential/vif-with-vfor.md
  docs/rules/vue-recommended/element-attribute-order.md
  docs/rules/vue-recommended/top-level-element-order.md
  docs/rules/vue-strong/component-filename-casing.md
  docs/rules/vue-strong/component-files.md
  docs/rules/vue-strong/directive-shorthands.md
  docs/rules/vue-strong/full-word-component-name.md
  docs/rules/vue-strong/multi-attribute-elements.md
  docs/rules/vue-strong/prop-name-casing.md
  docs/rules/vue-strong/quoted-attribute-values.md
  docs/rules/vue-strong/self-closing-components.md
  docs/rules/vue-strong/simple-computed.md
  docs/rules/vue-strong/template-simple-expression.md
Labels: enhancement

#147 fix: lowercased single-words should not raise warning
  src/rules/vue-strong/propNameCasing.test.ts
  src/rules/vue-strong/propNameCasing.ts
Labels: bug, needs-review

#150 feat: add new rule rrd - vfor with index key w tests
  docs/.vitepress/config.ts
  docs/rules/rrd/index.md
  docs/rules/rrd/v-for-with-index-key.md
  src/rules/rrd/vForWithIndexKey.test.ts
  src/rules/rrd/vForWithIndexKey.ts
  src/rules/rules.ts
  src/rulesCheck.ts
  src/rulesReport.ts
Labels: enhancement, needs-review

#148 feat: add --order flag plus some refactor
  README.md
  docs/get-started.md
  src/analyzer.ts
  src/helpers/constants.ts
  src/helpers/index.ts
  src/index.ts
  src/rulesReport.ts
  src/types/index.ts
Labels: enhancement, needs-review

#159 feat: add new rule rrd zero-length-comparison w tests
  docs/.vitepress/config.ts
  docs/rules/rrd/index.md
  docs/rules/rrd/zero-length-comparison.md
  src/rules/rrd/zeroLengthComparison.test.ts
  src/rules/rrd/zeroLengthComparison.ts
  src/rules/rules.ts
  src/rulesCheck.ts
  src/rulesReport.ts
Labels: enhancement, needs-review

#171 feat: add createMarkdown script to generate rule's details docs base …
  docs/contribute.md
  package.json
  src/generator/createMarkdown.js
  src/generator/ruleDetailsSkeleton
Labels: enhancement

#183 fix: huge refactor to the `functionSize.ts` check and parse methods plus more tests
  src/rules/rrd/functionSize.test.ts
  src/rules/rrd/functionSize.ts
Labels: bug

#191 feat: enable --apply/--ignore flags to handle rules and rulesets via command / config file
  dist/vue-mess-detector.es.js
  src/analyzer.ts
  src/helpers/calculateCodeHealth.ts
  src/helpers/coerceRules.ts
  src/helpers/constants.ts
  src/helpers/groupRulesByRuleset.ts
  src/index.test.ts
  src/index.ts
  src/rulesCheck.ts
  src/types/index.ts
Labels: enhancement
